from time import sleep

def menu_card():
    print("\t\t-------------------------------------------------------------------------")
    print(" \t\t                             Hotel TAJ")
    print("\t\t-------------------------------------------------------------------------")
    print(" \t\t                             Menu Card")
    print("\t\t-------------------------------------------------------------------------")
    sleep(1)
    print("\n\t\t BEVARAGES                              26 Dal Fry................ 350.00")
    print("\t\t----------------------------------      27 Dal Makhani............ 360.00")
    print("\t\t 1  Regular Tea............. 150.00     28 Dal Tadka.............. 380.00")
    print("\t\t 2  Masala Tea.............. 180.00")
    print("\t\t 3  Coffee.................. 200.00     ROTI")
    print("\t\t 4  Cold Drink.............. 180.00    ----------------------------------")
    print("\t\t 5  Bread Butter............ 150.00     29 Plain Roti.............. 35.00")
    print("\t\t 6  Bread Jam............... 150.00     30 Butter Roti............. 45.00")
    print("\t\t 7  Veg. Sandwich........... 180.00     31 Tandoori Roti........... 50.00")
    print("\t\t 8  Veg. Toast Sandwich..... 220.00     32 Butter Naan............. 60.00")
    print("\t\t 9  Cheese Toast Sandwich... 300.00")
    print("\t\t 10 Grilled Sandwich........ 280.00     RICE")
    sleep(1)
    print("\t\t                                       ----------------------------------")
    print("\t\t SOUPS                                  33 Plain Rice..............200.00")
    print("\t\t----------------------------------      34 Jeera Rice..............250.00")
    print("\t\t 11 Tomato Soup............ 250.00      35 Veg Pulao.............. 310.00")
    print("\t\t 12 Hot & Sour............. 250.00      36 Peas Pulao............. 350.00")
    print("\t\t 13 Veg. Noodle Soup....... 250.00")
    print("\t\t 14 Sweet Corn............. 260.00      SOUTH INDIAN")
    print("\t\t 15 Veg. Munchow........... 280.00     ----------------------------------")
    sleep(1)
    print("\t\t                                        37 Plain Dosa............. 300.00")
    print("\t\t MAIN COURSE                            38 Onion Dosa............. 330.00")
    print("\t\t----------------------------------      39 Masala Dosa............ 360.00")
    print("\t\t 16 Shahi Paneer........... 380.00      40 Paneer Dosa............ 420.00")
    print("\t\t 17 Kadai Paneer........... 360.00      41 Rice Idli.............. 320.00")
    print("\t\t 18 Handi Paneer........... 350.00      42 Sambhar Vada........... 350.00")
    print("\t\t 19 Palak Paneer........... 340.00")
    print("\t\t 20 Chilli Paneer.......... 400.00      ICE CREAM")
    print("\t\t 21 Matar Mushroom......... 380.00     ----------------------------------")
    print("\t\t 22 Mix Veg................ 360.00      43 Vanilla................. 180.00")
    print("\t\t 23 Jeera Aloo............. 340.00      44 Strawberry.............. 180.00")
    print("\t\t 24 Malai Kofta............ 370.00      45 Pineapple............... 180.00")
    print("\t\t 25 Aloo Matar............. 300.00      46 Butter Scotch........... 180.00")
