from time import sleep

def room_info():
    print("")
    print("  ","-"*10,"HOTEL ROOMS INFO","-"*10)
    print("")
    print("A CATEGORY ROOM")
    print("---------------------------------------------------------------")
    print("Room amenities include: 1 Double Bed + 1 Single Bed, Television,")
    print("Telephone, a Triple-Door Cupboard, 1 Coffee table with 4 sofa, 1")
    print("Side table, Balcony with an Accent table with 2 Chair and an")
    print("attached washroom with hot/cold water + Window/Split AC With 1 laptop stand with Confress table.\n")
    sleep(1)
    print("B CATEGORY ROOM")
    print("---------------------------------------------------------------")
    print("Room amenities include: 1 Double Bed + 1 Single Bed, Television,")
    print("Telephone, a Triple-Door Cupboard, 1 Coffee table with 2 sofa, 1")
    print("Side table, Balcony with an Accent table with 2 Chair and an")
    print("attached washroom with hot/cold water + Window/Split AC.\n")
    sleep(1)
    print("C CATEGORY ROOM")
    print("---------------------------------------------------------------")
    print("Room amenities include: 1 Double Bed, Television, Telephone,")
    print("Single-Door Cupboard, 1 Coffee table with 2 sofa, Small Balcony and")
    print("an attached washroom with hot/cold water + Window/Split AC.\n")
    sleep(1)
    print("D CATEGORY ROOM")
    print("---------------------------------------------------------------")
    print("Room amenities include: 1 Double Bed, Television, Telephone,")
    print("Single-Door Cupboard, 1 Coffee table with 2 sofa, Balcony and")
    print("an attached washroom with hot/cold water + Window/Split AC.\n")
    sleep(1)
    print("S CATEGORY ROOM")
    print("---------------------------------------------------------------")
    print("Room amenities include: 2 Double Bed + 1 Single Bed, Television,")
    print("Telephone, a Triple-Door Cupboard, 1 Coffee table with 4 sofa, ")
    print("1 Side table, Balcony with an Accent table with 2 Chair and an")
    print("attached washroom with hot/cold water + Window/Split AC With 1 laptop stand with Confress table.\n\n")
    sleep(1)